"""Interactive demo — shows ContextDuty catching a secret in under 20 seconds."""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
import time
from pathlib import Path

from .ui.output import style


def _print(msg: str = "") -> None:
    print(msg, flush=True)


def _step(msg: str) -> None:
    print(f"\n{style.bold}{style.cyan}▶ {msg}{style.reset}", flush=True)


def _ok(msg: str) -> None:
    print(f"{style.green}✓ {msg}{style.reset}", flush=True)


def _warn(msg: str) -> None:
    print(f"{style.yellow}⚠ {msg}{style.reset}", flush=True)


def _pause(seconds: float = 0.8) -> None:
    time.sleep(seconds)


# Realistic-looking fake secrets — assembled at runtime so GitHub push protection
# does not flag this source file. The detector engine matches on structure; none of
# these values are real credentials.
_AWS_KEY = "AKIA" + "CONTEXTDUTY0DEMO"
_OPENAI_KEY = "sk-proj-" + "EXAMPLEcontextdutyDEMOkeyXXXXXXXXXXXXXXXXXXXXXXXX"
_STRIPE_KEY = "sk" + "_live_EXAMPLEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"


def _fake_config() -> str:
    return (
        "# config.py — generated by deployment script\n"
        "# DO NOT COMMIT\n\n"
        'DATABASE_URL = "postgresql://admin:Sup3rS3cr3t!@prod-db.internal:5432/customers"\n\n'
        f'AWS_ACCESS_KEY_ID     = "{_AWS_KEY}"\n'
        'AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"\n\n'
        f'OPENAI_API_KEY = "{_OPENAI_KEY}"\n\n'
        f'STRIPE_SECRET_KEY = "{_STRIPE_KEY}"\n\n'
        'SUPPORT_EMAIL = "admin@yourcompany.com"\n'
    )


_FAKE_FIXTURE = """\
# tests/fixtures/customers.json
[
  {"id": 1, "name": "Jane Smith",   "email": "jane.smith@example.com",  "ssn": "123-45-6789"},
  {"id": 2, "name": "John Doe",     "email": "john.doe@example.com",    "phone": "+1-800-555-0199"},
  {"id": 3, "name": "Alice Martin", "email": "alice.martin@example.com","card": "4111111111111111"}
]
"""


def run_demo() -> None:
    _print()
    _print(f"{style.bold}{'─' * 60}{style.reset}")
    _print(f"{style.bold}  ContextDuty — Interactive Demo{style.reset}")
    _print(f"{style.dim}  Shows how secrets are caught before they reach an AI prompt{style.reset}")
    _print(f"{style.bold}{'─' * 60}{style.reset}")

    tmp = Path(tempfile.mkdtemp(prefix="contextduty-demo-"))
    try:
        _run_demo_in(tmp)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
        _print()
        _print(f"{style.dim}Demo directory cleaned up.{style.reset}")
        _print()


def _run_demo_in(tmp: Path) -> None:
    # ── Scene 1: developer creates a config file ─────────────────────────────
    _print()
    _step("Scene 1 — Developer creates config.py with real credentials")
    _pause()

    config_file = tmp / "config.py"
    fake_config = _fake_config()
    config_file.write_text(fake_config)
    _print(f"  {style.dim}$ cat config.py{style.reset}")
    _pause(0.4)
    for line in fake_config.strip().splitlines():
        _print(f"  {style.dim}{line}{style.reset}")
        time.sleep(0.03)

    # ── Scene 2: scan the file directly ──────────────────────────────────────
    _print()
    _step("Scene 2 — Scanning config.py")
    _print(f"  {style.dim}$ contextduty scan config.py{style.reset}")
    _pause(0.5)

    from .engine import scan_file
    from .policy import load_policy

    policy = load_policy(None)
    result = scan_file(config_file, policy)

    report = {
        "findings_count": result.findings_count,
        "detector_counts": result.detector_counts,
        "blocked": result.blocked,
    }
    _print()
    for line in json.dumps(report, indent=2).splitlines():
        color = (
            style.red
            if any(k in line for k in ("findings", "true", "aws", "openai", "email", "stripe"))
            else style.reset
        )
        _print(f"  {color}{line}{style.reset}")
        time.sleep(0.02)

    _print()
    _warn(
        f"{result.findings_count} sensitive values detected across {len(result.detector_counts)} detector(s)"
    )

    # ── Scene 3: redact it ───────────────────────────────────────────────────
    _print()
    _step("Scene 3 — Redacting config.py (safe to pass to AI)")
    _print(
        f"  {style.dim}$ contextduty redact --in config.py --out config.redacted.py{style.reset}"
    )
    _pause(0.5)

    from .engine import redact_file

    redacted_file = tmp / "config.redacted.py"
    redact_file(config_file, redacted_file, policy)

    _print()
    for line in redacted_file.read_text().strip().splitlines():
        is_masked = "<" in line and "_" in line
        color = style.green if is_masked else style.dim
        _print(f"  {color}{line}{style.reset}")
        time.sleep(0.03)

    _print()
    _ok("Real values replaced with deterministic masks — safe to paste into any AI tool")

    # ── Scene 4: pre-commit hook catching it ─────────────────────────────────
    _print()
    _step("Scene 4 — Pre-commit hook blocks the commit")
    _pause()

    # Set up a real git repo
    subprocess.run(["git", "init", str(tmp)], capture_output=True)
    subprocess.run(
        ["git", "-C", str(tmp), "config", "user.email", "demo@example.com"], capture_output=True
    )
    subprocess.run(["git", "-C", str(tmp), "config", "user.name", "Demo"], capture_output=True)

    from .hooks import install_git_hook

    install_git_hook(tmp)

    # Write a block-mode policy so the commit gets rejected
    block_policy = {
        "mode": "block",
        "detectors": ["aws_key", "openai_key", "stripe_key", "email"],
        "custom_detectors": {},
    }
    (tmp / ".contextduty.json").write_text(json.dumps(block_policy, indent=2))

    subprocess.run(
        ["git", "-C", str(tmp), "add", "config.py", ".contextduty.json"], capture_output=True
    )

    _print(f"  {style.dim}$ git add config.py && git commit -m 'add config'{style.reset}")
    _pause(0.8)

    commit_result = subprocess.run(
        ["git", "-C", str(tmp), "commit", "-m", "add config"],
        capture_output=True,
        text=True,
    )

    combined = (commit_result.stdout + commit_result.stderr).strip()
    _print()
    for line in combined.splitlines():
        if "BLOCKED" in line or "blocked" in line.lower() or "ContextDuty" in line:
            _print(f"  {style.red}{style.bold}{line}{style.reset}")
        elif "╔" in line or "║" in line or "╚" in line:
            _print(f"  {style.red}{line}{style.reset}")
        elif line.strip():
            _print(f"  {style.dim}{line}{style.reset}")

    if commit_result.returncode != 0:
        _print()
        _ok("Commit rejected — secrets never entered git history")
    else:
        _print()
        _warn("Hook did not fire (git hook requires contextduty in PATH during commit)")
        _print(
            f"  {style.dim}Run: contextduty install-hooks  in your own repo to activate{style.reset}"
        )

    # ── Scene 5: scan a directory (customer fixture file) ────────────────────
    _print()
    _step("Scene 5 — Scanning a test fixture with customer PII")
    _pause()

    fixtures_dir = tmp / "tests" / "fixtures"
    fixtures_dir.mkdir(parents=True)
    fixture_file = fixtures_dir / "customers.json"
    fixture_file.write_text(_FAKE_FIXTURE)

    _print(f"  {style.dim}$ contextduty scan tests/{style.reset}")
    _pause(0.5)

    from .engine import scan_dir

    pii_policy = load_policy(None)
    dir_result = scan_dir(fixtures_dir, pii_policy)

    dir_report = {
        "findings_count": dir_result.findings_count,
        "detector_counts": dir_result.detector_counts,
        "files_scanned": len(dir_result.files_scanned),
    }
    _print()
    for line in json.dumps(dir_report, indent=2).splitlines():
        color = (
            style.red
            if any(k in line for k in ("findings", "email", "phone", "ssn", "card"))
            else style.reset
        )
        _print(f"  {color}{line}{style.reset}")
        time.sleep(0.02)

    _print()
    _warn(
        f"{dir_result.findings_count} PII values found — if a developer pastes this fixture into Cursor, all of it goes to OpenAI"
    )

    # ── Summary ───────────────────────────────────────────────────────────────
    _print()
    _print(f"{style.bold}{'─' * 60}{style.reset}")
    _print(f"{style.bold}  What just happened{style.reset}")
    _print(f"{'─' * 60}")
    _print(
        f"  {style.green}✓{style.reset}  Scanned config.py — found {result.findings_count} secrets across {len(result.detector_counts)} detectors"
    )
    _print(f"  {style.green}✓{style.reset}  Redacted all values — safe masked output ready for AI")
    _print(
        f"  {style.green}✓{style.reset}  Pre-commit hook blocked commit containing AWS + OpenAI keys"
    )
    _print(
        f"  {style.green}✓{style.reset}  Directory scan found PII in test fixtures before Cursor could index them"
    )
    _print(f"{'─' * 60}")
    _print()
    _print(f"{style.bold}  Next steps{style.reset}")
    _print()
    _print("  Install the hook in your repo:")
    _print(f"    {style.cyan}contextduty install-hooks{style.reset}")
    _print()
    _print("  Use with Claude / Cursor via MCP — add to ~/.cursor/mcp.json:")
    _print(
        f'    {style.cyan}{{"mcpServers": {{"contextduty": {{"command": "contextduty-mcp"}}}}}}{style.reset}'
    )
    _print()
    _print("  View the audit dashboard:")
    _print(f"    {style.cyan}contextduty dashboard --demo{style.reset}")
    _print()
    _print(f"  Docs: {style.cyan}https://github.com/SHUBHAGYTA24/contextduty{style.reset}")
    _print(f"{style.bold}{'─' * 60}{style.reset}")
    _print()
